spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: chat-server
  datasource:
    url: jdbc:mysql://${swchat.mysql.ip}:${swchat.mysql.port}/${swchat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${swchat.mysql.username}
    password: ${swchat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${swchat.redis.host}
    # Redis服务器端口号
    port: ${swchat.redis.port}
    # 使用的数据库索引，默认是0
    database: ${swchat.redis.database}
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${swchat.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
# 配置mp控制台打印sql语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wx:
  mp:
    #    callback:
    callback: ${swchat.wx.callback}
    configs:
      - appId: ${swchat.wx.appId} # 第一个公众号的appid
        secret: ${swchat.wx.secret} # 公众号的appsecret
        token: ${swchat.wx.token} # 接口配置里的Token值
        aesKey: ${swchat.wx.aesKey} # 接口配置里的EncodingAESKey值
jwt:
  secret: ${swchat.jwt.secret}